apiVersion: v1
kind: ConfigMap
metadata:
  name: ${USER_NAME}-${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
  labels:
    app: ${USER_NAME}-${SERVICE_NAME}
    component: config
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "SKALA DevOps Study - Jenkins based CI/CD"
      numExecutors: 10
      mode: NORMAL

      securityRealm:
        local:
          allowsSignup: true
          users:
            - id: "admin"
              password: "admin"
            - id: "sk000"
              password: "skala"
            - id: "sk001"
              password: "skala"
            - id: "sk002"
              password: "skala"
            - id: "sk003"
              password: "skala"
            - id: "sk004"
              password: "skala"
            - id: "sk005"
              password: "skala"
            - id: "sk006"
              password: "skala"
            - id: "sk007"
              password: "skala"
            - id: "sk008"
              password: "skala"
            - id: "sk009"
              password: "skala"
            - id: "sk010"
              password: "skala"
            - id: "sk011"
              password: "skala"
            - id: "sk012"
              password: "skala"
            - id: "sk013"
              password: "skala"
            - id: "sk014"
              password: "skala"
            - id: "sk015"
              password: "skala"
            - id: "sk016"
              password: "skala"
            - id: "sk017"
              password: "skala"
            - id: "sk018"
              password: "skala"
            - id: "sk019"
              password: "skala"
            - id: "sk020"
              password: "skala"
            - id: "sk021"
              password: "skala"
            - id: "sk022"
              password: "skala"
            - id: "sk023"
              password: "skala"
            - id: "sk024"
              password: "skala"
            - id: "sk025"
              password: "skala"
            - id: "sk026"
              password: "skala"
            - id: "sk027"
              password: "skala"
            - id: "sk028"
              password: "skala"
            - id: "sk029"
              password: "skala"
            - id: "sk030"
              password: "skala"
            - id: "sk031"
              password: "skala"
            - id: "sk032"
              password: "skala"
            - id: "sk033"
              password: "skala"
            - id: "sk034"
              password: "skala"
            - id: "sk035"
              password: "skala"
            - id: "sk036"
              password: "skala"
            - id: "sk037"
              password: "skala"
            - id: "sk038"
              password: "skala"
            - id: "sk039"
              password: "skala"
            - id: "sk040"
              password: "skala"
            - id: "sk041"
              password: "skala"
            - id: "sk042"
              password: "skala"
            - id: "sk043"
              password: "skala"
            - id: "sk044"
              password: "skala"
            - id: "sk045"
              password: "skala"
            - id: "sk046"
              password: "skala"
            - id: "sk047"
              password: "skala"
            - id: "sk048"
              password: "skala"
            - id: "sk049"
              password: "skala"
            - id: "sk050"
              password: "skala"
            - id: "sk051"
              password: "skala"
            - id: "sk052"
              password: "skala"
            - id: "sk053"
              password: "skala"
            - id: "sk054"
              password: "skala"
            - id: "sk055"
              password: "skala"
            - id: "sk056"
              password: "skala"
            - id: "sk057"
              password: "skala"
            - id: "sk058"
              password: "skala"
            - id: "sk059"
              password: "skala"
            - id: "sk060"
              password: "skala"
            - id: "sk061"
              password: "skala"
            - id: "sk062"
              password: "skala"
            - id: "sk063"
              password: "skala"
            - id: "sk064"
              password: "skala"
            - id: "sk065"
              password: "skala"
            - id: "sk066"
              password: "skala"
            - id: "sk067"
              password: "skala"
            - id: "sk068"
              password: "skala"
            - id: "sk069"
              password: "skala"
            - id: "sk070"
              password: "skala"
            - id: "sk071"
              password: "skala"
            - id: "sk072"
              password: "skala"
            - id: "sk073"
              password: "skala"
            - id: "sk074"
              password: "skala"
            - id: "sk075"
              password: "skala"
            - id: "sk076"
              password: "skala"
            - id: "sk077"
              password: "skala"
            - id: "sk078"
              password: "skala"
            - id: "sk079"
              password: "skala"
            - id: "sk080"
              password: "skala"
            - id: "sk081"
              password: "skala"
            - id: "sk082"
              password: "skala"
            - id: "sk083"
              password: "skala"
            - id: "sk084"
              password: "skala"
            - id: "sk085"
              password: "skala"
            - id: "sk086"
              password: "skala"
            - id: "sk087"
              password: "skala"
            - id: "sk088"
              password: "skala"
            - id: "sk089"
              password: "skala"
            - id: "sk090"
              password: "skala"
            - id: "sk091"
              password: "skala"
            - id: "sk092"
              password: "skala"
            - id: "sk093"
              password: "skala"
            - id: "sk094"
              password: "skala"
            - id: "sk095"
              password: "skala"
            - id: "sk096"
              password: "skala"
            - id: "sk097"
              password: "skala"
            - id: "sk098"
              password: "skala"
            - id: "sk099"
              password: "skala"
            - id: "sk100"
              password: "skala"
            - id: "sk101"
              password: "skala"
            - id: "sk102"
              password: "skala"
            - id: "sk103"
              password: "skala"
            - id: "sk104"
              password: "skala"
            - id: "sk105"
              password: "skala"
            - id: "sk106"
              password: "skala"
            - id: "sk107"
              password: "skala"
            - id: "sk108"
              password: "skala"
            - id: "sk109"
              password: "skala"
            - id: "sk110"
              password: "skala"
            - id: "sk111"
              password: "skala"
            - id: "sk112"
              password: "skala"
            - id: "sk113"
              password: "skala"
            - id: "sk114"
              password: "skala"
            - id: "sk115"
              password: "skala"
            - id: "sk116"
              password: "skala"
            - id: "sk117"
              password: "skala"
            - id: "sk118"
              password: "skala"
            - id: "sk119"
              password: "skala"
            - id: "sk120"
              password: "skala"

      authorizationStrategy:
        globalMatrix:
          permissions:
            - "Overall/Administer:admin"
            - "Overall/Read:authenticated"
            - "View/Read:authenticated"
            - "Job/Discover:authenticated"
            - "Job/Read:authenticated"
            - "Job/Build:authenticated"
            - "Job/Configure:authenticated"
            - "Job/Create:authenticated"

    unclassified:
      location:
        url: "https://jenkins.skala25a.project.skala-ai.com/"
        adminAddress: "skala@skala-ai.com"
