apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk199-custom-jenkins-pvc
  namespace: skala-practice
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc-shared
