apiVersion: v1
kind: Service
metadata:
  name: sk199-custom-jenkins
  namespace: skala-practice
spec:
  selector:
    app: sk199-custom-jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: jnlp
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


